### ISSUE TITLE
Running `sbt compile` gives an error: scala.reflect.internal.MissingRequirementError: class stainless.lang.MutableMap

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless-actors#8]
The error is:

> [error] (Compile / compileIncremental) scala.reflect.internal.MissingRequirementError: class stainless.lang.MutableMap in compiler mirror not found

I guess this is because we shouldn't run `sbt compile`, but rather `sbt actors/compile` if we just want to compile the actors?

**Comment by romac** [comment]
Can't reproduce anymore.
